language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools
    #- android-ndk-r15c

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
#before_script:

before_install:
    - chmod +x gradlew
    - pushd $TRAVIS_BUILD_DIR/..
    - wget https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip -O ndk.zip
    - chmod a+x ndk.zip
    - unzip ndk.zip > /dev/null
    - rm ndk.zip
    - export ANDROID_NDK_HOME=`pwd`/android-ndk-r15c
    - export PATH=$PATH:$ANDROID_NDK_HOME
    - echo $PATH
    - popd

#script:
#    - ./gradlew build
